name: CMake on a specific platform

on:
  push:
    branches: [ "develop", "master"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          include:
            - os: ubuntu-latest
              triplet: x64-linux
              preset: dev

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.2.1
        with:
          cache: 'true'
          version: '6.9.0'

      - name: Download libxcb-cursor0
        if: runner.os == 'Linux'
        run: |
          ldd /home/runner/work/qt_test_github_actions/Qt/6.9.0/gcc_64/plugins/platforms/libqxcb.so | grep "not found"
          sudo apt-get update --fix-missing
          sudo apt-get install -y \
            libfontconfig1 \
            libxcb1 \
            libfontconfig1-dev \
            libfreetype6-dev \
            libx11-dev \
            libxcursor-dev \
            libxext-dev \
            libxfixes-dev \
            libxft-dev \
            libxi-dev \
            libxrandr-dev \
            libxrender-dev \
            libxkbcommon-x11-0

      - name: Run Cmake
        env:
          QT_DEBUG_PLUGINS: 1
        run:
          cmake --workflow --preset ${{ matrix.preset }}
