name: CMake on a specific platform

on:
  push:
    branches: [ "develop", "master"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          include:
            - os: ubuntu-latest
              preset: dev
            - os: ubuntu-24.04-arm
              preset: dev
            - os: windows-2022
              preset: dev
            - os: windows-11-arm
              preset: dev
            - os: macos-15
              preset: dev
            - os: macos-13
              preset: dev

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Qt
        uses: jdpurcell/install-qt-action@v5
        with:
          cache: 'true'
          version: '6.9.0'
          modules: 'qtdatavis3d qt5compat'

      - name: Init MSVC
        uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
        with:
          arch: ${{ runner.arch == 'ARM64' && 'arm64' || 'x64' }}

      - name: Prepare linux build env
        if: runner.os == 'Linux'
        run: |
          echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV    

      - name: Run Cmake
        run:
          cmake --workflow --preset ${{ matrix.preset }}
