name: CMake on a specific platform

on:
  push:
    branches: [ "develop", "master"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          include:
            - os: ubuntu-latest
              triplet: x64-linux
              preset: dev

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.2.1
        with:
          cache: 'true'
          version: '6.9.0'
      - name: Run Cmake
        env:
          QT_DEBUG_PLUGINS: 1
          QT_QPA_PLATFORM: "offscreen"
        run:
          cmake --workflow --preset ${{ matrix.preset }}
