name: CMake on a specific platform

on:
  push:
    branches: [ "develop", "master"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          include:
            - os: ubuntu-latest
              preset: dev
            - os: ubuntu-24.04-arm
              preset: dev

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.2.1
        with:
          cache: 'true'
          version: '6.9.0'

      - name: Prepare linux build env
        if: runner.os == 'Linux'
        run: |
          echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV    

      - name: Run Cmake
        env:
          QT_DEBUG_PLUGINS: 1
        run:
          cmake --workflow --preset ${{ matrix.preset }}
