name: CMake on a specific platform

on:
  push:
    branches: [ "develop", "master"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          include:
            - os: ubuntu-latest
              preset: dev
              qt_host: linux
              qt_arch: linux_gcc_64
            - os: ubuntu-24.04-arm
              preset: dev
              qt_host: linux_arm64
              qt_arch: linux_gcc_arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Qt
        uses: jdpurcell/install-qt-action@v5
        with:
          aqtversion: '==3.2.*'
          cache: 'true'
          version: '6.9.0'
          host: ${{ matrix.qt_host }}
          arch: ${{ matrix.qt_arch }}

      - name: Prepare linux build env
        if: runner.os == 'Linux'
        run: |
          echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV    

      - name: Run Cmake
        env:
          QT_DEBUG_PLUGINS: 1
        run:
          cmake --workflow --preset ${{ matrix.preset }}
